#!/usr/bin/env bash

# Start a new day of Advent of Code 2024
# Usage: ./start day01

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

function usage() {
  echo "Usage: ./start day01"
}

function main() {
  if [ $# -ne 1 ]; then
      echo "ERROR: no day was provided"
      usage
      exit 1
  fi

  local day="$1"

  if [[ ! "$day" =~ ^day[0-9]{2}$ ]]; then
    echo "ERROR: invalid input: $day"
    usage
    exit 1
  fi

  echo
  echo "Advent of code 2024 - $day"
  echo

  # Check if folder already exists
  if [ -d "$day" ]; then
    echo "ERROR: folder already exists"
    usage
    exit 1
  fi

  echo -n "Generating day..."

  mkdir "$day" && cd "$day"
  cp -r "$PROJECT_DIR"/day00/* .
  mv day00.mjs "$day".mjs
  sed -i '' "s/day00/$day/g" "$day".mjs

  cd $PROJECT_DIR

  echo "done"

  echo -n "Doing a test run..."

  node ./$day/$day.mjs > /dev/null

  if [ $? -eq 0 ]; then
    echo "done"
  else
    echo "ERROR: something went wrong"
    exit 1
  fi

  echo
  echo "All done!"
  echo
  echo "node ./$day/$day.mjs"
}

main "$@"
